name: Damn Vulnerable DeFi V3 CTF

default_ecosystem: ethereum
ethereum:
  default_network: local
  local:
    default_provider: foundry

foundry:
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy
        block_number: 15450164 

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.7.1
  - name: safe-global
    github: safe-global/safe-contracts
    version: 1.3.0

solidity: 
  import_remapping:
    - "@openzeppelin=OpenZeppelin/4.7.1"
    - "@gnosis.pm/safe-contracts=safe-global/1.3.0"

plugins:
  - name: vyper
  - name: solidity
  - name: foundry
  - name: alchemy
  - name: etherscan
